### ISSUE TITLE
Not working on iOS latest version 13.3

### ISSUE THREAD

**Issue by csprasad** [pablogsIO/GeometricLoaders#2]
i have been trying to add this loader to my project but it's not working i tried both ways using cocoapods and manual for both its not working loader not appear when called.

**Comment by pablogsIO** [comment]
Hello, thank you very much for your interest in this library. 

- Could you please attach some code? 

- have you try to clone the project and see if it works on 13.3?

Regards

**Comment by yasodha-r** [comment]
Hi,

I too have same problem. Its not showing up in latest ios ios13+.
Steps:
1. Created new project
2. copied n pasted files under Geometric folder
3. In viewcontroller.swft,
class ViewController: UIViewController {
    var geometricLoader = GeometricLoader()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        self.view.backgroundColor = UIColor.gray
    }
    
     override func viewDidAppear(_ animated: Bool) {
            super.viewDidAppear(animated)
            geometricLoader = Infinity.createGeometricLoader()
            geometricLoader.startAnimation()
    }
}

It works in example project you have in github. Please check

Thank you

**Comment by pablogsIO** [comment]
Thanks @yasodha-r for the steps to reproduce it. Could you please change the method setupView of GeometricLoader class with this one? Does it work?

```swift
internal func setupView() {
        
	var window: UIWindow?

	if #available(iOS 13.0, *) {
		let sceneDelegate = UIApplication.shared.connectedScenes.first!.delegate as! SceneDelegate
		window = sceneDelegate.window
	} else {
		window = UIApplication.shared.delegate?.window as? UIWindow
	}
        guard let mainWindow = window else {
			print("No window available")
			return
		}
        
        self.frame = mainWindow.frame
        self.center = CGPoint(x: mainWindow.bounds.midX, y: mainWindow.bounds.midY)
        
        mainWindow.addSubview(self)
        
        self.loaderSuperview = mainWindow
        self.loaderView.frame = CGRect(x: frame.origin.x, y: frame.origin.y, width: frame.width/2, height: frame.width/2)
        self.loaderView.center = CGPoint(x: frame.width/2, y: frame.height/2)
        self.loaderView.backgroundColor = UIColor.clear
        self.isHidden = true
        self.addSubview(loaderView)
        
    }
```

**Comment by yasodha-r** [comment]
It works now. Thank you 😊 @pablogsIO

**Comment by csprasad** [comment]
Thank you 🤩 @pablogsIO
